### ISSUE TITLE
Prep-Intro Page

### ISSUE THREAD

**Issue by yazchar** [yazchar/FL40K-Maelstrom-Mixer-2019#2]
Information for the Intro Page found:
https://docs.google.com/document/d/1D9ZEe2-8j9TRcbu9BsWfLu-I-8biIT6_4674BA4e65E/edit

- time/place
- Flavor text
- Welcome message
- Imagery

**Comment by Unillu** [comment]
@yazchar 
I need the information for Friday/Saturday night updated in the doc. Thanks!

**Comment by Unillu** [comment]
Hi @yazchar, I've uploaded the L/S comps to this folder:
https://drive.google.com/drive/folders/1lNWDpf0RXuL5OnMUOdHzR0ztc4mI1PCn?usp=sharing

Images are FPO, let's discuss which images we want to replace them with.

**Comment by Unillu** [comment]
FPO Images were replaced and the comps are being reviewed by Bill, will add notes here.

**Comment by Unillu** [comment]
@yazchar  Page ready for review. 

Link for local test: http://localhost:8890/maelstrom-mixer-june-2019/
Milestones explained: https://docs.google.com/document/d/1urXuQaNtwnUh3THe1IT5zifMqrecbJC0WfD4Rw4npaQ/edit?usp=sharing
Milestone calendar: https://docs.google.com/spreadsheets/d/11VaT0EblVrNfqWf_CFVTl5I9VwU91qXGKFWoU_woUBk/edit?usp=sharing

**Comment by Unillu** [comment]
Added OG image. Page is complete.
